//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPrincipal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyFranchiseSpecial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyFranchiseSpecial()
        {
            this.CompanyFranchiseSpecialFiles = new HashSet<CompanyFranchiseSpecialFile>();
            this.CompanyFranchiseSpecialLocations = new HashSet<CompanyFranchiseSpecialLocation>();
            this.CompanyFranchiseSpecialVieweds = new HashSet<CompanyFranchiseSpecialViewed>();
            this.CompanyFranchiseSpecialRatingsAndComments = new HashSet<CompanyFranchiseSpecialRatingsAndComment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyFranchiseId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string PromoCode { get; set; }
        public string Details { get; set; }
        public string ProductType { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAvailableOnline { get; set; }
        public int CompanyFranchiseSpecialCategoryId { get; set; }
        public System.DateTime AuditCreatedDate { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditLastUpdatedDate { get; set; }
        public string AuditLastUpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual CompanyFranchise CompanyFranchise { get; set; }
        public virtual CompanyFranchiseSpecialCategory CompanyFranchiseSpecialCategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseSpecialFile> CompanyFranchiseSpecialFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseSpecialLocation> CompanyFranchiseSpecialLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseSpecialViewed> CompanyFranchiseSpecialVieweds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseSpecialRatingsAndComment> CompanyFranchiseSpecialRatingsAndComments { get; set; }
    }
}
