//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPrincipal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyFranchise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyFranchise()
        {
            this.CompanyFranchiseFollowedByUsers = new HashSet<CompanyFranchiseFollowedByUser>();
            this.CompanyFranchiseRatingsAndComments = new HashSet<CompanyFranchiseRatingsAndComment>();
            this.CompanyFranchiseSpecials = new HashSet<CompanyFranchiseSpecial>();
            this.CompanyFranchiseUsers = new HashSet<CompanyFranchiseUser>();
            this.CompanyFranchiseVieweds = new HashSet<CompanyFranchiseViewed>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int AddressId { get; set; }
        public int CompanyFranchiseCategoryId { get; set; }
        public int CreatedById { get; set; }
        public bool CanOrderOnline { get; set; }
        public bool CanContactCustomers { get; set; }
        public bool CanGetCustomerDetails { get; set; }
        public string ConfirmationToken { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsConfirmed { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedDate { get; set; }
        public System.DateTime AuditLastUpdatedDate { get; set; }
        public string AuditLastUpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        public virtual CompanyFranchiseCategory CompanyFranchiseCategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseFollowedByUser> CompanyFranchiseFollowedByUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseRatingsAndComment> CompanyFranchiseRatingsAndComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseSpecial> CompanyFranchiseSpecials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseUser> CompanyFranchiseUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFranchiseViewed> CompanyFranchiseVieweds { get; set; }
    }
}
