//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPrincipal.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyLocalSpecialsEntities : DbContext
    {
        public MyLocalSpecialsEntities()
            : base("name=MyLocalSpecialsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ApplicationSetting> ApplicationSettings { get; set; }
        public virtual DbSet<ApplicationSettingType> ApplicationSettingTypes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyAddress> CompanyAddresses { get; set; }
        public virtual DbSet<CompanyFollowedByUser> CompanyFollowedByUsers { get; set; }
        public virtual DbSet<CompanyFranchise> CompanyFranchises { get; set; }
        public virtual DbSet<CompanyFranchiseCategory> CompanyFranchiseCategories { get; set; }
        public virtual DbSet<CompanyFranchiseFollowedByUser> CompanyFranchiseFollowedByUsers { get; set; }
        public virtual DbSet<CompanyFranchiseRatingsAndComment> CompanyFranchiseRatingsAndComments { get; set; }
        public virtual DbSet<CompanyFranchiseSpecial> CompanyFranchiseSpecials { get; set; }
        public virtual DbSet<CompanyFranchiseSpecialCategory> CompanyFranchiseSpecialCategories { get; set; }
        public virtual DbSet<CompanyFranchiseSpecialFile> CompanyFranchiseSpecialFiles { get; set; }
        public virtual DbSet<CompanyFranchiseSpecialLocation> CompanyFranchiseSpecialLocations { get; set; }
        public virtual DbSet<CompanyFranchiseSpecialRatingsAndComment> CompanyFranchiseSpecialRatingsAndComments { get; set; }
        public virtual DbSet<CompanyFranchiseSpecialViewed> CompanyFranchiseSpecialVieweds { get; set; }
        public virtual DbSet<CompanyFranchiseUser> CompanyFranchiseUsers { get; set; }
        public virtual DbSet<CompanyFranchiseViewed> CompanyFranchiseVieweds { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FriendInvitation> FriendInvitations { get; set; }
        public virtual DbSet<PermissionType> PermissionTypes { get; set; }
        public virtual DbSet<RefreshToken> RefreshTokens { get; set; }
        public virtual DbSet<SecurityObject> SecurityObjects { get; set; }
        public virtual DbSet<SecurityObjectType> SecurityObjectTypes { get; set; }
        public virtual DbSet<ShareAnythingPost> ShareAnythingPosts { get; set; }
        public virtual DbSet<ShareAnythingPostAddress> ShareAnythingPostAddresses { get; set; }
        public virtual DbSet<ShareAnythingPostComment> ShareAnythingPostComments { get; set; }
        public virtual DbSet<ShareAnythingPostFile> ShareAnythingPostFiles { get; set; }
        public virtual DbSet<ShareAnythingPostLike> ShareAnythingPostLikes { get; set; }
        public virtual DbSet<ShareAnythingPostLink> ShareAnythingPostLinks { get; set; }
        public virtual DbSet<ShareAnythingPostType> ShareAnythingPostTypes { get; set; }
        public virtual DbSet<ShareAnythingReport> ShareAnythingReports { get; set; }
        public virtual DbSet<ShareAnythingReportSeverity> ShareAnythingReportSeverities { get; set; }
        public virtual DbSet<ShareAnythingReportType> ShareAnythingReportTypes { get; set; }
        public virtual DbSet<UserFriendList> UserFriendLists { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webpages_RolesPermission> webpages_RolesPermission { get; set; }
        public virtual DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
    }
}
