//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPrincipal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareAnythingPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShareAnythingPost()
        {
            this.ShareAnythingPostAddresses = new HashSet<ShareAnythingPostAddress>();
            this.ShareAnythingPostComments = new HashSet<ShareAnythingPostComment>();
            this.ShareAnythingPostFiles = new HashSet<ShareAnythingPostFile>();
            this.ShareAnythingPostLikes = new HashSet<ShareAnythingPostLike>();
            this.ShareAnythingReports = new HashSet<ShareAnythingReport>();
        }
    
        public int Id { get; set; }
        public int PostedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Details { get; set; }
        public int ShareAnythingPostTypeId { get; set; }
        public Nullable<int> ShareAnythingPostLinkId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime AuditCreatedDate { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditLastUpdatedDate { get; set; }
        public string AuditLastUpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual User User { get; set; }
        public virtual ShareAnythingPostLink ShareAnythingPostLink { get; set; }
        public virtual ShareAnythingPostType ShareAnythingPostType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareAnythingPostAddress> ShareAnythingPostAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareAnythingPostComment> ShareAnythingPostComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareAnythingPostFile> ShareAnythingPostFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareAnythingPostLike> ShareAnythingPostLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareAnythingReport> ShareAnythingReports { get; set; }
    }
}
