//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPrincipal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareAnythingReport
    {
        public int Id { get; set; }
        public int ShareAnythingReportTypeId { get; set; }
        public int ShareAnythingReportSeverityId { get; set; }
        public System.DateTime ReportedDate { get; set; }
        public string ReportDetails { get; set; }
        public int ReportByUserId { get; set; }
        public int ReportOfUserId { get; set; }
        public int ShareAnythingPostId { get; set; }
        public bool IsOpen { get; set; }
        public bool IsReportValid { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime AuditCreatedDate { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditLastUpdatedDate { get; set; }
        public string AuditLastUpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ShareAnythingPost ShareAnythingPost { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ShareAnythingReportSeverity ShareAnythingReportSeverity { get; set; }
        public virtual ShareAnythingReportType ShareAnythingReportType { get; set; }
    }
}
